config/routes.rb
Rails.application.routes.draw do

  get  'homes/show' => 'homes#show'

  get 'homes/index' => 'crops#index'

  get 'homes' => 'crops#index'

  resources :crops

  root 'homes#show'

end

app/models/crop.rb
class Crop < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController

  def new
    @crop = Crop.new
  end

  def create
    @crop = Crop.create(crop_params)
    if @crop.valid?
      redirect_to @crop
    else
      render :new
    end
  end

  def show
    @crop = Crop.find(params[:id])
  end

  def index
    @crops = Crop.all
  end

  def edit
    @crop = Crop.find(params[:id])
  end

  def update

  end

  private

  def crop_params
    params.require(:crop).permit(:name, :description)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def show

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crops_helper.rb
module CropsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/crops/_form.html.erb
<%= form_for @crop do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control", autofocus:true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f. text_field :description, class:"form-control" %>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>

<% end %>

app/views/crops/edit.html.erb
<%= render 'form'%>

app/views/crops/index.html.erb
<h1>Crops</h1>

<h3> <%= link_to 'Plant something lovely!', new_crop_path %> </h3>

<table class='table'>

  <thead>
  <th>Name</th>
  <th>Description</th>
  <th> </th>
  </thead>


  <% @crops.each do |crop| %>
  <tr>
    <td>
      <%= crop.name %>
    </td>
    <td>
      <%= crop.description %>
    </td>
    <td>
      <%= link_to 'Edit', edit_crop_path(crop.id) %>
    </td>
  </tr>

  <% end %>

</table>

app/views/crops/new.html.erb
<h1>A shiny new crop</h1>


<%= render 'form'%>

app/views/crops/show.html.erb
<h1><%= @crop.name %></h1>

<p>
  <%= @crop.description %>
</p>

<%= link_to 'Return to the garden', crops_path%>

app/views/homes/show.html.erb
<h1>My Garden</h1>

<%= link_to 'Plant a crop!', new_crop_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garden</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>